# Generated by Django 4.2.5 on 2023-10-03 16:11

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog_app', '0003_blogcomments'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='blogComments',
            new_name='BlogComment',
        ),
    ]
